/// Use or operation of this code is subject to acceptance of the license available in the code repository for this code.
Class DataMining.ClusterAnalysis.GraphicalDemoApp Extends %ZEN.application
{

/// This is the name of this application.
Parameter APPLICATIONNAME = "Cluster Analysis Demo";

/// This is the URL of the main starting page of this application.
Parameter HOMEPAGE;

/// This Style block contains application-wide CSS style definitions.
XData Style
{
<style type="text/css">
</style>
}

}

